# Generated by Django 3.2 on 2023-07-05 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_user_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together=set(),
        ),
    ]
