# Generated by Django 3.2 on 2023-07-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_title_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='date',
        ),
        migrations.AddField(
            model_name='title',
            name='year',
            field=models.IntegerField(blank=True, help_text='Выберите дату релиза', null=True, verbose_name='Дата релиза'),
        ),
    ]
