# Generated by Django 3.2 on 2023-07-05 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_rename_rating_review_score'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='review_unique',
        ),
    ]
