# Generated by Django 3.2 on 2023-07-05 09:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0009_review_review_unique'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='review_unique',
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('author', 'title')},
        ),
    ]
